// web/src/lib/components/FloorPanel.svelte
<script lang="ts">
  // The floor panel (§4.1): overall status, per-class buckets, then the `sentences` and
  // `disclosure` display texts, verbatim (§4.2 rule 5). Colour never carries meaning
  // alone (rule 7): every status word is present, and a null is a dash, never zero.
  import Chip from "./Chip.svelte";
  import Fraction from "./Fraction.svelte";

  type Bucket = {
    basis_count: number | null;
    found: number | null;
    needed: number | null;
    floor: number;
    meets_floor: boolean;
    [k: string]: unknown;
  };
  export type FloorPanelData = {
    overall: {
      basis: string;
      basis_count: number | null;
      found: number | null;
      rate: number | null;
      floor: number;
      floor_version: number;
      floor_set_at: string;
      status: string;
      final: boolean;
      blocking: string[];
      [k: string]: unknown;
    };
    by_class: Record<string, Bucket>;
    sentences: string[];
    disclosure: string;
    [k: string]: unknown;
  } | null;

  let { panel }: { panel: FloorPanelData } = $props();
</script>

{#if panel}
  <section>
    <h3>floor and deficit</h3>
    <p class="line">
      {panel.overall.basis}
      <Fraction numerator={panel.overall.basis_count} /> /
      <Fraction numerator={panel.overall.found} /> =
      <strong>{panel.overall.rate === null ? "—" : panel.overall.rate.toFixed(2)}</strong>
      · floor {panel.overall.floor}
      · v{panel.overall.floor_version}
      · {panel.overall.floor_set_at}
      · <Chip text={panel.overall.status} />
      {#if panel.overall.blocking.length}
        <span class="muted">not final: {panel.overall.blocking.join(", ")}</span>
      {/if}
    </p>
    {#if Object.keys(panel.by_class).length}
      <table>
        <thead>
          <tr><th>class</th><th>basis / found</th><th>needed</th><th>floor</th><th></th></tr>
        </thead>
        <tbody>
          {#each Object.entries(panel.by_class) as [name, bucket] (name)}
            <tr>
              <td class="mono">{name}</td>
              <td><Fraction numerator={bucket.basis_count} /> / <Fraction numerator={bucket.found} /></td>
              <td><Fraction numerator={bucket.needed} /></td>
              <td>{bucket.floor}</td>
              <td><Chip text={bucket.meets_floor ? "meets" : "below"} /></td>
            </tr>
          {/each}
        </tbody>
      </table>
    {/if}
    {#each panel.sentences as sentence (sentence)}
      <p class="note">{sentence}</p>
    {/each}
    <p class="note">{panel.disclosure}</p>
  </section>
{/if}

<style>
  .line {
    margin: 0.25rem 0;
  }
  .note {
    color: var(--muted);
    font-size: 0.85rem;
    margin: 0.25rem 0;
  }
  .muted {
    color: var(--muted);
    font-size: 0.85rem;
  }
  table {
    border-collapse: collapse;
    margin: 0.5rem 0;
  }
  th,
  td {
    border: 1px solid var(--border);
    padding: 0.2rem 0.5rem;
    text-align: left;
  }
  .mono {
    font-family: ui-monospace, Menlo, Consolas, monospace;
  }
</style>

// web/src/components/FloorPanel.tsx
import { CategoryBar } from "@/components/tremor/CategoryBar/CategoryBar";
import Chip from "@/components/Chip";
import Fraction from "@/components/Fraction";
import type { Overview } from "@/lib/api-types";

// §8.3 item 5: the floor panel per class — a CategoryBar with a marker at each
// class's floor, then the deficit `sentences` and the `disclosure` verbatim (rule 5).
// Colour never carries meaning alone (rule 7): the status word is always present,
// and a null is a dash, never a zero (rule 1).

type Bucket = {
  basis: string;
  basis_count: number | null;
  found: number | null;
  needed: number | null;
  floor: number;
  meets_floor: boolean;
};

type FloorPanelData = {
  overall: {
    basis: string;
    basis_count: number | null;
    found: number | null;
    rate: number | null;
    floor: number;
    floor_version: number;
    floor_set_at: string;
    status: string;
    final: boolean;
    blocking: string[];
  };
  by_class: Record<string, Bucket>;
  sentences: string[];
  disclosure: string;
};

export default function FloorPanel({ panel }: { panel: Overview["floor_panel"] }) {
  if (panel === null) return null;
  const data = panel as unknown as FloorPanelData;
  const classes = Object.entries(data.by_class);
  return (
    <section className="rounded-lg bg-card p-5 shadow-sm ring-1 ring-gray-200 dark:ring-gray-800">
      <h2 className="text-base font-semibold">Floor and deficit</h2>
      <p className="mt-1 flex flex-wrap items-baseline gap-2 text-sm">
        <span>
          {data.overall.basis} <Fraction numerator={data.overall.basis_count} /> /{" "}
          <Fraction numerator={data.overall.found} /> =
        </span>
        <strong>
          {data.overall.rate === null ? (
            <span title="not knowable">—</span>
          ) : (
            data.overall.rate.toFixed(2)
          )}
        </strong>
        <span>· floor {data.overall.floor}</span>
        <span>· v{data.overall.floor_version}</span>
        <span>· {data.overall.floor_set_at}</span>
        <Chip text={data.overall.status} />
        {data.overall.blocking.length > 0 ? (
          <span className="text-xs text-muted-foreground">
            not final: {data.overall.blocking.join(", ")}
          </span>
        ) : null}
      </p>
      {classes.length > 0 ? (
        <div className="mt-4 flex flex-col gap-4">
          {classes.map(([name, bucket]) => (
            <div key={name} data-floor-class={name}>
              <div className="flex flex-wrap items-baseline justify-between gap-2 text-sm">
                <span className="font-mono text-[13px]">{name}</span>
                <span className="text-xs text-muted-foreground">
                  <Fraction numerator={bucket.basis_count} /> / <Fraction numerator={bucket.found} />{" "}
                  {bucket.basis} · needed <Fraction numerator={bucket.needed} /> · floor{" "}
                  {bucket.floor}
                </span>
                <Chip text={bucket.meets_floor ? "meets" : "below"} />
              </div>
              {bucket.found !== null && bucket.found > 0 ? (
                <CategoryBar
                  values={[
                    bucket.basis_count ?? 0,
                    Math.max(bucket.found - (bucket.basis_count ?? 0), 0),
                  ]}
                  colors={["emerald", "gray"]}
                  marker={{ value: bucket.floor * bucket.found, tooltip: `floor ${bucket.floor}` }}
                  showLabels={false}
                  className="mt-1.5 max-w-md"
                />
              ) : null}
            </div>
          ))}
        </div>
      ) : null}
      {data.sentences.map((sentence, index) => (
        <p key={`${index}-${sentence}`} className="mt-2 text-sm text-muted-foreground">
          {sentence}
        </p>
      ))}
      <p className="mt-2 text-sm text-muted-foreground">{data.disclosure}</p>
    </section>
  );
}
