// web/src/lib/components/InboxCards.svelte
<script lang="ts">
  // The inbox cards (§4.1): server order preserved (§4.2 rule 6) — this component never
  // sorts, ranks or filters; `cause`, `note` and `command` are display text rendered
  // verbatim (rule 5). A command is text to copy, never a button that runs anything
  // (rule 4) — the copy affordance is CommandBlock's, and it never executes.
  import CommandBlock from "./CommandBlock.svelte";

  export type InboxCard = {
    category: string;
    scope: string;
    subject: string;
    cause: string;
    command: string | null;
    note: string;
    [k: string]: unknown;
  };

  let { cards }: { cards: InboxCard[] } = $props();
</script>

<div class="cards">
  {#each cards as card, index (index)}
    <div class="card" data-card-index={index}>
      <span class="category">{card.category}</span>
      <span class="scope mono">{card.scope}</span>
      <div class="body">
        <strong>{card.subject}</strong> — {card.cause}
        {#if card.command}
          <CommandBlock command={card.command} />
        {/if}
        {#if card.note}
          <p class="note">{card.note}</p>
        {/if}
      </div>
    </div>
  {:else}
    <p class="note">nothing open in this scope</p>
  {/each}
</div>

<style>
  .cards {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  .card {
    display: grid;
    grid-template-columns: 8rem 12rem 1fr;
    gap: 0.75rem;
    border: 1px solid var(--border);
    border-radius: 0.5rem;
    padding: 0.4rem 0.6rem;
    align-items: baseline;
  }
  .category {
    font-weight: 600;
  }
  .mono {
    font-family: ui-monospace, Menlo, Consolas, monospace;
    font-size: 0.8rem;
  }
  .body {
    min-width: 0;
  }
  .note {
    color: var(--muted);
    font-size: 0.8rem;
    margin: 0.25rem 0 0;
  }
</style>

// web/src/components/InboxCards.tsx
import CommandBlock from "@/components/CommandBlock";
import type { Inbox } from "@/lib/api-types";

export type InboxCard = Inbox["cards"][number];

// The inbox cards (§4.1): server order preserved (§4.2 rule 6) — this component never
// sorts, ranks or filters. `cause`, `note` and `command` are display text rendered
// verbatim (rule 5); a command is text to copy, never something the page runs (rule 4)
// — the copy affordance is CommandBlock's, and it never executes.
export default function InboxCards({ cards }: { cards: InboxCard[] }) {
  if (cards.length === 0) {
    return (
      <p className="text-sm text-muted-foreground">nothing open in this scope</p>
    );
  }
  return (
    <div className="flex flex-col gap-2">
      {cards.map((card, index) => (
        <div
          key={index}
          data-card-index={index}
          className="grid items-baseline gap-3 rounded-lg border border-border bg-card px-3 py-2 md:grid-cols-[8rem_12rem_1fr]"
        >
          <span className="text-sm font-semibold">{card.category}</span>
          <span className="font-mono text-xs text-muted-foreground">
            {card.scope}
          </span>
          <div className="min-w-0 text-sm">
            <strong>{card.subject}</strong> — {card.cause}
            {card.command ? <CommandBlock command={card.command} /> : null}
            {card.note ? (
              <p className="mt-1 text-xs text-muted-foreground">{card.note}</p>
            ) : null}
          </div>
        </div>
      ))}
    </div>
  );
}
