// web/src/lib/components/QuestionMatrix.svelte
<script lang="ts">
  // The question matrix (§4.1): registry order, per-class counts before the total
  // (§4.2 rule 2), the five verdicts plus dashed engine states (rule 3), every display
  // text verbatim (rule 5). An operator filter is the only allowed sorting (rule 6);
  // none is offered here — the server order is the order.
  import Chip from "./Chip.svelte";
  import Fraction from "./Fraction.svelte";

  export type MatrixRow = {
    id: string;
    kind: string;
    text: string;
    claims_by_class: Record<string, number>;
    claims: number | null;
    coverage: { sources: number | null; examined: number | null };
    direction_count: Record<string, unknown>;
    direction_count_note: string;
    gate_rejected_total: number;
    awaiting_review: number;
    state: string | null;
    provisional: boolean;
    blocking: string[];
    verdict: string | null;
    verdict_stale: boolean;
    unavailable: string;
    operational_not_applicable: boolean;
    note: string | null;
    [k: string]: unknown;
  };

  let {
    rows,
    base = "",
  }: { rows: MatrixRow[]; base?: string } = $props();
</script>

<section>
  <h3>the questions — registry order</h3>
  <table>
    <thead>
      <tr>
        <th>id</th><th>question</th><th>kind</th><th>claims per class</th>
        <th>coverage<br />speaking / examined</th><th>direction count</th>
        <th>gate rejected</th><th>awaiting review</th><th>verdict</th>
      </tr>
    </thead>
    <tbody>
      {#each rows as row (row.id)}
        <tr data-question-id={row.id}>
          <td class="mono">
            {#if base}
              <a href={`${base}/q/${encodeURIComponent(row.id)}`}>{row.id}</a>
            {:else}{row.id}{/if}
          </td>
          <td>{row.text}</td>
          <td>{row.kind}</td>
          <td>
            {#each Object.entries(row.claims_by_class) as [name, count] (name)}
              <span class="by-class" data-class={name}>{name} {count}</span>
            {:else}
              <span title="not knowable">—</span>
            {/each}
            <span class="muted">→ <Fraction numerator={row.claims} /> total</span>
          </td>
          <td>
            {#if row.coverage.sources === null}
              <span title="not knowable">— / —</span>
            {:else}
              {row.coverage.sources} / {row.coverage.examined}
            {/if}
          </td>
          <td>
            {#if Object.keys(row.direction_count).length}
              {#each Object.entries(row.direction_count) as [name, count] (name)}
                <span>{name} {String(count)}</span>
              {/each}
              <span class="muted">({row.direction_count_note})</span>
            {:else}
              <span title="not knowable">—</span>
            {/if}
          </td>
          <td>{row.gate_rejected_total}</td>
          <td>{row.awaiting_review}</td>
          <td>
            {#if row.operational_not_applicable}
              <Chip text="LITERATURE_VERDICT_NOT_APPLICABLE" /><br />
              <span class="muted">kind operational: no verdict</span>
            {:else if row.verdict}
              <Chip text={row.verdict} />
              {#if row.verdict_stale}<Chip text="stale" />{/if}
            {:else if row.state === "NO_VERIFIED_CLAIM"}
              <Chip text="NO_VERIFIED_CLAIM" />
            {:else if row.state}
              <Chip text={row.state} />
            {:else}
              <span class="chip dashed" title="not knowable">— no verdict</span>
            {/if}
            {#if row.provisional}
              <br /><Chip text={row.blocking.join(", ") || "provisional"} />
            {/if}
            {#if row.unavailable}
              <br /><span class="muted">historical — {row.unavailable}</span>
            {/if}
            {#if row.note}
              <br /><span class="muted">{row.note}</span>
            {/if}
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
  <p class="note">
    Claims are counted per class before they are pooled (invariant 6).
    NO_VERIFIED_CLAIM is the engine's categorical outcome and never a verdict: only a
    person can say <q>never asked</q>. No pooling, no R: a person reads the profile and signs.
  </p>
</section>

<style>
  table {
    border-collapse: collapse;
  }
  th,
  td {
    border: 1px solid var(--border);
    padding: 0.2rem 0.5rem;
    text-align: left;
    vertical-align: top;
  }
  .mono {
    font-family: ui-monospace, Menlo, Consolas, monospace;
  }
  .muted {
    color: var(--muted);
    font-size: 0.8rem;
  }
  .by-class {
    margin-right: 0.4rem;
  }
  .chip {
    display: inline-block;
    border: 1px dashed var(--border);
    border-radius: 0.5rem;
    padding: 0.05rem 0.45rem;
    font-size: 0.75rem;
    color: var(--muted);
  }
  .note {
    color: var(--muted);
    font-size: 0.85rem;
  }
</style>

// web/src/components/QuestionMatrix.tsx
import { Link } from "react-router";
import Chip from "@/components/Chip";
import Fraction from "@/components/Fraction";
import type { Overview } from "@/lib/api-types";

// The questions table (§8.3): registry order, per-class counts before the total
// (§4.2 rule 2), a mini bar of direction counts labelled with the counts and the
// server's note verbatim (rules 1 and 5), the five verdicts plus dashed engine
// states (rule 3). The server's row order is the DOM order — no operator filter
// is offered here, so none can reorder it (rule 6).
export type MatrixRow = Overview["questions"]["rows"][number];

// The direction segments are coloured by position, never by meaning: the words
// beside the bar carry the meaning (rule 7).
const SEGMENT_COLORS = ["bg-blue-500", "bg-sky-500", "bg-gray-300", "bg-indigo-400"];

export default function QuestionMatrix({
  rows,
  base = "",
}: {
  rows: MatrixRow[];
  base?: string;
}) {
  return (
    <div>
      <table className="w-full min-w-[620px] border-collapse text-sm">
        <thead>
          <tr className="border-b border-border text-left text-foreground">
            <th className="p-2 font-semibold">ID</th>
            <th className="p-2 font-semibold">Question</th>
            <th className="p-2 font-semibold">Per class → total</th>
            <th className="p-2 font-semibold">Direction (count)</th>
            <th className="p-2 font-semibold">Status</th>
          </tr>
        </thead>
        <tbody className="text-muted-foreground">
          {rows.map((row) => {
            const directions = Object.entries(row.direction_count).map(
              ([name, count]) => [name, Number(count)] as const,
            );
            return (
              <tr key={row.id} data-question-id={row.id} className="border-b border-border/60">
                <td className="p-3 font-mono text-[13px] text-foreground">
                  {base ? (
                    <Link
                      to={`${base}/q/${encodeURIComponent(row.id)}`}
                      className="text-blue-600 hover:underline dark:text-blue-400"
                    >
                      {row.id}
                    </Link>
                  ) : (
                    row.id
                  )}
                </td>
                <td className="max-w-[280px] whitespace-normal p-3">{row.text}</td>
                <td className="p-3 font-mono text-[13px]">
                  {Object.keys(row.claims_by_class).length === 0 ? (
                    <span title="not knowable">—</span>
                  ) : (
                    Object.entries(row.claims_by_class).map(([name, count]) => (
                      <span key={name} className="by-class mr-1.5" data-class={name}>
                        {name} {count}
                      </span>
                    ))
                  )}
                  <span className="text-muted-foreground">
                    → <Fraction numerator={row.claims} /> total
                  </span>
                </td>
                <td className="p-3">
                  {directions.length === 0 ? (
                    <span title="not knowable">—</span>
                  ) : (
                    <>
                      <div className="flex h-1.5 w-[120px] gap-px" aria-hidden="true">
                        {directions.map(([name, count], index) => (
                          <div
                            key={name}
                            className={SEGMENT_COLORS[index % SEGMENT_COLORS.length]}
                            style={{ flexGrow: Math.max(count, 1) }}
                          />
                        ))}
                      </div>
                      <span className="text-xs">
                        {directions.map(([name, count]) => `${name} ${count}`).join(" · ")}{" "}
                        ({row.direction_count_note})
                      </span>
                    </>
                  )}
                </td>
                <td className="p-3">
                  {row.operational_not_applicable ? (
                    <>
                      <Chip text="LITERATURE_VERDICT_NOT_APPLICABLE" />
                      <br />
                      <span className="text-xs">kind operational: no verdict</span>
                    </>
                  ) : row.verdict ? (
                    <>
                      <Chip text={row.verdict} />
                      {row.verdict_stale ? <Chip text="stale" /> : null}
                    </>
                  ) : row.state === "NO_VERIFIED_CLAIM" ? (
                    <Chip text="NO_VERIFIED_CLAIM" />
                  ) : row.state ? (
                    <Chip text={row.state} />
                  ) : (
                    <span className="chip dashed" title="not knowable">
                      — no verdict
                    </span>
                  )}
                  {row.provisional ? (
                    <>
                      <br />
                      <Chip text={row.blocking.join(", ") || "provisional"} />
                    </>
                  ) : null}
                  {row.unavailable ? (
                    <>
                      <br />
                      <span className="text-xs">historical — {row.unavailable}</span>
                    </>
                  ) : null}
                  {row.note ? (
                    <>
                      <br />
                      <span className="text-xs">{row.note}</span>
                    </>
                  ) : null}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
      <p className="mt-2 text-xs text-muted-foreground">
        Claims are counted per class before they are pooled (invariant 6).
        NO_VERIFIED_CLAIM is the engine's categorical outcome and never a verdict:
        only a person can say "never asked". No pooling, no R: a person reads the
        profile and signs.
      </p>
    </div>
  );
}
