// web/src/components/IntegrityPanel.tsx
import Chip from "@/components/Chip";
import type { Integrity } from "@/lib/api-types";

// Integrity (§4.1): can these numbers be trusted now. Every state is a named chip with
// its word (§4.2 rule 7); a null is a dash with the "not knowable" title, never a zero
// (rule 1). Display text (`error` strings) is rendered verbatim (rule 5).
export default function IntegrityPanel({ integrity }: { integrity: Integrity }) {
  const ledgerEntries = Object.entries(integrity.ledgers).sort(([a], [b]) =>
    a.localeCompare(b),
  );
  return (
    <section className="rounded-lg border border-border bg-card p-4">
      <h3 className="text-sm font-semibold">
        integrity — can these numbers be trusted now
      </h3>
      <p className="mt-2 text-sm">
        <b>config</b> <Chip text={integrity.config.state} />{" "}
        {integrity.config.error ? (
          <span className="text-sm text-muted-foreground">{integrity.config.error}</span>
        ) : null}
      </p>
      <p className="mt-1 text-sm">
        <b>registry</b> <Chip text={integrity.registry.state} />{" "}
        {integrity.registry.error ? (
          <span className="text-sm text-muted-foreground">{integrity.registry.error}</span>
        ) : null}
      </p>
      <p className="mt-1 text-sm">
        <b>ledger repairs</b> {integrity.ledger_repairs}
      </p>
      <p className="mt-1 text-sm">
        <b>orphans</b>{" "}
        {integrity.orphans === null ? (
          <span title="not knowable">—</span>
        ) : (
          integrity.orphans
        )}
      </p>
      {integrity.invalid_flows.map((fid) => (
        <p key={fid} className="mt-1 flex flex-wrap items-baseline gap-2 text-sm">
          <b>invalid flow row</b>
          <Chip text="id is not the hash of its binding" />
          <span className="font-mono text-xs">{fid.slice(0, 16)}</span>
        </p>
      ))}
      <p className="mt-1 text-sm">
        <b>instruments</b>{" "}
        {integrity.instruments.length ? (
          <>
            <Chip text="NOT acknowledged" />
            {integrity.instruments.map((problem) => (
              <span key={problem} className="block text-sm text-muted-foreground">
                {problem}
              </span>
            ))}
          </>
        ) : (
          <Chip text="acknowledged" />
        )}
      </p>
      <p className="mt-1 text-sm">
        <b>code</b> {(integrity.code.revision ?? "unknown").slice(0, 12)}
        {integrity.code.dirty ? " · dirty" : ""} · grobid{" "}
        {(integrity.code.grobid_image ?? "").slice(0, 40)}
      </p>
      {ledgerEntries.map(([name, entry]) => (
        <p key={name} className="mt-1 flex flex-wrap items-baseline gap-2 text-sm">
          <span className="font-mono text-xs">{name}</span>
          <span>· {entry?.rows} rows</span>
          {entry?.torn_tail ? <Chip text="torn tail" /> : null}
          {entry?.error ? <Chip text={entry.error} /> : null}
        </p>
      ))}
    </section>
  );
}

// web/src/lib/components/IntegrityPanel.svelte
<script lang="ts">
  // Integrity (§4.1): can these numbers be trusted now. Every state is a named chip
  // with its word (§4.2 rule 7); a null is a dash, never zero (rule 1).
  import type { Integrity } from "$lib/api-types";
  import Chip from "./Chip.svelte";

  let { integrity }: { integrity: Integrity } = $props();
</script>

<section>
  <h3>integrity — can these numbers be trusted now</h3>
  <p class="line"><b>config</b> <Chip text={integrity.config.state} />
    {#if integrity.config.error}<span class="note">{integrity.config.error}</span>{/if}</p>
  <p class="line"><b>registry</b> <Chip text={integrity.registry.state} />
    {#if integrity.registry.error}<span class="note">{integrity.registry.error}</span>{/if}</p>
  <p class="line"><b>ledger repairs</b> {integrity.ledger_repairs}</p>
  <p class="line"><b>orphans</b>
    {#if integrity.orphans === null}<span title="not knowable">—</span>{:else}{integrity.orphans}{/if}</p>
  {#each integrity.invalid_flows as fid (fid)}
    <p class="line"><b>invalid flow row</b> <Chip text="id is not the hash of its binding" />
      <span class="mono">{fid.slice(0, 16)}</span></p>
  {/each}
  <p class="line"><b>instruments</b>
    {#if integrity.instruments.length}
      <Chip text="NOT acknowledged" />
      {#each integrity.instruments as problem (problem)}
        <br /><span class="note">{problem}</span>
      {/each}
    {:else}
      <Chip text="acknowledged" />
    {/if}</p>
  <p class="line"><b>code</b> {(integrity.code.revision ?? "unknown").slice(0, 12)}
    {#if integrity.code.dirty}· dirty{/if}
    · grobid {(integrity.code.grobid_image ?? "").slice(0, 40)}</p>
  {#each Object.entries(integrity.ledgers).toSorted(([a], [b]) => String(a).localeCompare(String(b))) as [name, entry] (name)}
    <p class="line">
      <span class="mono">{name}</span> · {entry?.rows} rows
      {#if entry?.torn_tail}· <Chip text="torn tail" />{/if}
      {#if entry?.error}· <Chip text={entry.error} />{/if}
    </p>
  {/each}
</section>

<style>
  .line {
    margin: 0.25rem 0;
  }
  .note {
    color: var(--muted);
    font-size: 0.85rem;
  }
  .mono {
    font-family: ui-monospace, Menlo, Consolas, monospace;
  }
</style>
